### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by iLynette** [zmekonnen251/Leadboard#3]
- Hi, @zmekonnen251 your project works great and it can send and receive data from an API.

- [x] There is one thing you need to fix though, please remove the uncommented line of code in your index.js file, it will help your code look cleaner.
- [x] When you click on submit without input there's an error in the console, please put a condition that will check for that
Happy coding and all the best.

**Comment by zmekonnen251** [comment]
- Thank you partners :+1: :pray: for your constructive feedback. I will make the changes based on your comments.
